// limpiar datos para silver 
CREATE OR REPLACE TABLE SILVER_PEDIDOS_LIMPIOS AS
SELECT
  TO_NUMBER(ID) AS PedidoID,
  TRY_TO_DATE(FECHA_PEDIDO, 'YYYY-MM-DD') AS FechaPedido,
  TO_NUMBER(CLIENTE_ID) AS ClienteID,
  TO_NUMBER(PRODUCTO_ID) AS ProductoID,
  TO_NUMBER(CANTIDAD) AS Cantidad
FROM PEDIDOS_RAW
WHERE
  TRY_TO_NUMBER(ID) IS NOT NULL
  AND TRY_TO_DATE(FECHA_PEDIDO, 'YYYY-MM-DD') IS NOT NULL
  AND TRY_TO_NUMBER(CLIENTE_ID) IS NOT NULL
  AND TRY_TO_NUMBER(PRODUCTO_ID) IS NOT NULL
  AND TRY_TO_NUMBER(CANTIDAD) IS NOT NULL;

// Sanity check de como queda silver
SELECT * from SILVER_PEDIDOS_LIMPIOS
